/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Body: THREE.Mesh;
  };
  materials: {}; // eslint-disable-line @typescript-eslint/no-empty-object-type
};

export function Body(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/static/models/TruckBody.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={nodes.Body.material}
      />
    </group>
  );
}

useGLTF.preload("/static/models/TruckBody.glb");
